[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "santorar", email = "estractor179@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "alembic>=1.19.1",
    "bcrypt>=5.0.0",
    "fastapi[standard]>=0.141.1",
    "psycopg2-binary>=2.9.12",
    "pydantic-settings>=2.15.0",
    "sqlalchemy>=2.0.52",
]

[project.scripts]
backend = "backend:main"

[build-system]
requires = ["uv_build>=0.12.7,<0.13.0"]
build-backend = "uv_build"

[tool.uv]
package = false

