"""Crear base de datos inicial

Revision ID: 398bf60e74a9
Revises: 
Create Date: 2026-08-29 18:53:09.263986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '398bf60e74a9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empresa',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('nit', sa.String(), nullable=False),
    sa.Column('dv', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_empresa_id'), 'empresa', ['id'], unique=False)
    op.create_table('estado',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_estado_id'), 'estado', ['id'], unique=False)
    op.create_table('puc',
    sa.Column('codigo', sa.String(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('naturaleza', sa.CHAR(length=1), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.CheckConstraint("naturaleza IN ('D', 'C')", name='chk_naturaleza'),
    sa.PrimaryKeyConstraint('codigo')
    )
    op.create_index(op.f('ix_puc_codigo'), 'puc', ['codigo'], unique=False)
    op.create_table('tipo_documento',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tipo_documento_id'), 'tipo_documento', ['id'], unique=False)
    op.create_table('periodo_contable',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=False),
    sa.Column('estado_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['estado_id'], ['estado.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_periodo_contable_id'), 'periodo_contable', ['id'], unique=False)
    op.create_table('tercero',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('numero_documento', sa.String(), nullable=False),
    sa.Column('tipo_documento_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tipo_documento_id'], ['tipo_documento.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tercero_id'), 'tercero', ['id'], unique=False)
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('correo', sa.String(), nullable=False),
    sa.Column('clave_encriptada', sa.String(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuario_correo'), 'usuario', ['correo'], unique=True)
    op.create_index(op.f('ix_usuario_id'), 'usuario', ['id'], unique=False)
    op.create_index(op.f('ix_usuario_nombre'), 'usuario', ['nombre'], unique=False)
    op.create_table('comprobante',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_actualizacion', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('periodo_contable_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('estado_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], ),
    sa.ForeignKeyConstraint(['estado_id'], ['estado.id'], ),
    sa.ForeignKeyConstraint(['periodo_contable_id'], ['periodo_contable.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comprobante_id'), 'comprobante', ['id'], unique=False)
    op.create_table('linea_contable',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('descripcion', sa.String(), nullable=True),
    sa.Column('debito', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('credito', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('cuenta', sa.String(), nullable=False),
    sa.Column('tercero_id', sa.Integer(), nullable=True),
    sa.Column('comprobante_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['comprobante_id'], ['comprobante.id'], ),
    sa.ForeignKeyConstraint(['cuenta'], ['puc.codigo'], ),
    sa.ForeignKeyConstraint(['tercero_id'], ['tercero.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_linea_contable_id'), 'linea_contable', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_linea_contable_id'), table_name='linea_contable')
    op.drop_table('linea_contable')
    op.drop_index(op.f('ix_comprobante_id'), table_name='comprobante')
    op.drop_table('comprobante')
    op.drop_index(op.f('ix_usuario_nombre'), table_name='usuario')
    op.drop_index(op.f('ix_usuario_id'), table_name='usuario')
    op.drop_index(op.f('ix_usuario_correo'), table_name='usuario')
    op.drop_table('usuario')
    op.drop_index(op.f('ix_tercero_id'), table_name='tercero')
    op.drop_table('tercero')
    op.drop_index(op.f('ix_periodo_contable_id'), table_name='periodo_contable')
    op.drop_table('periodo_contable')
    op.drop_index(op.f('ix_tipo_documento_id'), table_name='tipo_documento')
    op.drop_table('tipo_documento')
    op.drop_index(op.f('ix_puc_codigo'), table_name='puc')
    op.drop_table('puc')
    op.drop_index(op.f('ix_estado_id'), table_name='estado')
    op.drop_table('estado')
    op.drop_index(op.f('ix_empresa_id'), table_name='empresa')
    op.drop_table('empresa')
    # ### end Alembic commands ###
