"""creacion de tablas para exogena y uvt

Revision ID: 7261e183ff0d
Revises: 6vr4gc58g9h2
Create Date: 2026-08-31 13:52:18.814886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7261e183ff0d'
down_revision: Union[str, Sequence[str], None] = '6vr4gc58g9h2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
