"""creacion de campos para trazabilidad de modificacion de comprobantes contabilizados

Revision ID: adb182fa86fc
Revises: 398bf60e74a9
Create Date: 2026-08-29 22:23:42.791609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'adb182fa86fc'
down_revision: Union[str, Sequence[str], None] = '398bf60e74a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comprobante', sa.Column('fecha_contabilizacion', sa.DateTime(), nullable=True))
    op.add_column('comprobante', sa.Column('comprobante_reversor_id', sa.Integer(), nullable=True))
    op.add_column('comprobante', sa.Column('comprobante_sustituto_id', sa.Integer(), nullable=True))
    op.add_column('comprobante', sa.Column('comprobante_original_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'comprobante', 'comprobante', ['comprobante_original_id'], ['id'])
    op.create_foreign_key(None, 'comprobante', 'comprobante', ['comprobante_sustituto_id'], ['id'])
    op.create_foreign_key(None, 'comprobante', 'comprobante', ['comprobante_reversor_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comprobante', type_='foreignkey')
    op.drop_constraint(None, 'comprobante', type_='foreignkey')
    op.drop_constraint(None, 'comprobante', type_='foreignkey')
    op.drop_column('comprobante', 'comprobante_original_id')
    op.drop_column('comprobante', 'comprobante_sustituto_id')
    op.drop_column('comprobante', 'comprobante_reversor_id')
    op.drop_column('comprobante', 'fecha_contabilizacion')
    # ### end Alembic commands ###
