"""agregar_campo_activo_tercero

Revision ID: b05c1ee690b8
Revises: cfbf673c2342
Create Date: 2026-08-30 12:19:32.793185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b05c1ee690b8'
down_revision: Union[str, Sequence[str], None] = 'cfbf673c2342'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tercero', sa.Column('activo', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tercero', 'activo')
    # ### end Alembic commands ###
