"""agregar_campo_activo_empresa_usuario

Revision ID: cfbf673c2342
Revises: b1c2d3e4f5g6
Create Date: 2026-08-30 12:07:58.875641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfbf673c2342'
down_revision: Union[str, Sequence[str], None] = 'b1c2d3e4f5g6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('empresa', sa.Column('activo', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    op.add_column('usuario', sa.Column('activo', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'activo')
    op.drop_column('empresa', 'activo')
    # ### end Alembic commands ###
